Model:
  # path to .ckpt file containing model weights that was saved after training
  weights_path: '/Users/paul/Desktop/UROP/checkpoints/updated_model.ckpt'
  # names of classes to predict
  class_names: ['APERIODIC', 'CONSTANT', 'CONTACT_ROT', 'DSCT_BCEP', 'ECLIPSE', 'GDOR_SPB', 'RRLYR_CEPH', 'SOLARLIKE']

Inference:
  # directory to output predictions, plots
  output_dir: '/Users/paul/Desktop/UROP/tess-wavelets/sector_26output/'
  # inference batch size
  batch_size: 64
  # if produce_plots is true, will plot lightcurve and its power spectrum 
  # along with its output probabilities. Can take a while with large number of 
  # predictions, not recommended when performing inference on large datasets such as 
  # entire TESS sectors
  produce_plots: True
  # device to run on. Cuda recommended if available. 
  device: 'mps'


Data:
  # if you have tensors already saved as .pt files, set tensors_saved_on_device to True, 
  # put the paths to the files for time_tensor, flux_tensor, tic_tensor below. 
  tensors_saved_on_device: True
  time_tensor: '/Users/paul/Desktop/UROP/Tensors/sector26_flux_tensor.pt'
  flux_tensor: '/Users/paul/Desktop/UROP/Tensors/sector26_time_tensor.pt'
  tic_tensor: '/Users/paul/Desktop/UROP/Tensors/sector26_ticids_tensor.pt'
  # data should be a directory of .fits files. 
  # if tess_preprocess is True, light curves are preprocessed as described in section 
  # 4.2.2 of Gregory et al. (2025). sequence length should be the maximim number of time steps
  # in the data (should be fairly consistent for all lightcurves)
  data_path: '/Users/paul/Desktop/UROP/data/tessv1/'
  seq_len: 1171
  num_workers: 4
  tess_preprocess: True
