[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "astrafier"
version = "1.0.0"
description = "Light-curve classifier for TESS"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "astropy",
  "Bottleneck",
  "huggingface_hub",
  "lightkurve",
  "matplotlib",
  "numpy",
  "pandas",
  "pytorch-lightning",
  "PyYAML",
  "safetensors",
  "scikit-learn",
  "scipy",
  "torch",
  "torchmetrics",
  "tqdm",
]

[project.optional-dependencies]
dev = ["black", "isort", "mypy", "pytest", "ruff"]

[project.scripts]
astrafier = "astrafier.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F"]
ignore = ["E203", "E501"]

