class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCwAAADE0MTIyNDkzMjE2cQJYAwAAAGNwdXEDSwhOdHEEUS6AAl1xAFgLAAAAMTQxMjI0
    OTMyMTZxAWEuCAAAAAAAAAAuiiBBfT8FQVHWa0DemSxBEM4IQTiBU0GVUgZDpw2UQA==
- 0
- !!python/tuple
  - 8
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
lr: 0.0006
num_classes: 8
optimizer_kwargs: {}
transformer_kwargs:
  dropout_p: 0.05
  emb: 32
  heads: 4
  hidden: 64
  layers: 1
